### ISSUE TITLE
Go back to wrapping libraries?

### ISSUE THREAD

**Issue by g2p** [g2p/mirage-storage#63]
The original reason not to wrap might have had to do with C bindings.
In any case it should be easy to remove if we wish to.
It's an API change and slightly more awkward to use however.

**Comment by samoht** [comment]
Why is it more awkward to use?

**Comment by g2p** [comment]
I was thinking that forcing the user to use dotted names would be an incompatible change and force more verbose usage.
But looking at the docs a module with the same name as the library gets special cased which allows to expose the right interfaces, so this isn't actually a problem.

**Comment by g2p** [comment]
Done by @pascutto.
